#!/bin/bash

echo "🚀 Setting up NestFest for Production"
echo "======================================"

# Production URL
PROD_URL="https://nestfest-9c7vvx6gp-abel-rincons-projects.vercel.app"

echo "📋 Manual Steps Required:"
echo ""
echo "1. Update Google OAuth (console.cloud.google.com):"
echo "   Add redirect URI: $PROD_URL/api/auth/callback/google"
echo ""
echo "2. Update GitHub OAuth (github.com/settings/developers):"
echo "   Set callback URL: $PROD_URL/api/auth/callback/github"  
echo ""
echo "3. Configure Vercel Environment Variables:"
echo "   Go to: https://vercel.com/abel-rincons-projects/nestfest/settings/environment-variables"
echo ""
echo "   Add these variables (copy from .env.local):"
echo "   - NEXTAUTH_URL=$PROD_URL"
echo "   - NEXTAUTH_SECRET=BDTVeLmqhQzXNzF7NMfaZ1JcCANmYDre7qF2A/wOd6M="
echo "   - POSTGRES_URL"
echo "   - GOOGLE_CLIENT_ID"  
echo "   - GOOGLE_CLIENT_SECRET"
echo "   - GITHUB_CLIENT_ID"
echo "   - GITHUB_CLIENT_SECRET"
echo ""
echo "4. Remove Deployment Protection:"
echo "   Go to: https://vercel.com/abel-rincons-projects/nestfest/settings/deployment-protection"
echo "   Set to 'Off' or use password protection for beta testing"
echo ""
echo "5. Deploy updated changes:"
echo "   git add . && git commit -m 'production: OAuth config' && git push && vercel --prod"
echo ""
echo "✅ After setup, test at: $PROD_URL"